### ISSUE TITLE
Example ISR_Modify_PWM.ino does not compile 

### ISSUE THREAD

**Issue by LyricDev** [khoih-prog/ESP32_PWM#1]
Tried compiling the example and saw the following errors. Using ESP32 core versions 2.0.1 and 2.0.0 in Arduino IDE v1.8.16. I'm not sure if its my mistake or if the example is out of date?

Arduino: 1.8.16 (Mac OS X), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 115200, Core 1, Core 1, None"

/Users/kd/Documents/Arduino/esp32_libraries_test/esp32_libraries_test.ino: In function 'void setup()':
esp32_libraries_test:123:74: error: void value not ignored as it ought to be
   channelNum = ISR_PWM.setPWM_Period(PWM_Pin, PWM_Period1, PWM_DutyCycle1);
                                                                          ^
/Users/kd/Documents/Arduino/esp32_libraries_test/esp32_libraries_test.ino: In function 'void changePWM()':
esp32_libraries_test:152:16: error: 'class ESP32_PWM' has no member named 'modifyPWMChannel'; did you mean 'setupPWMChannel'?
   if (!ISR_PWM.modifyPWMChannel(channelNum, PWM_Pin, PWM_Freq, PWM_DutyCycle))
                ^~~~~~~~~~~~~~~~
                setupPWMChannel
exit status 1
void value not ignored as it ought to be

**Comment by LyricDev** [comment]
My mistake, I was mistakenly using an older version of the ESP32_PWM library (1.0.1). After upgrading to v1.1.0 compiles OK!

**Comment by khoih-prog** [comment]
Good to know that's it's OK to you.

It's better to use the latest [**ESP32_PWM releases v1.1.1**](https://github.com/khoih-prog/ESP32_PWM/releases/tag/v1.1.1) for `ESP32 core v2.0.1+`
